---
- name: Configure Prometheus and Grafana.
  hosts: all
  become: yes
  vars:
    grafana_tls_cert_path: '/etc/letsencrypt/live/{{ inventory_hostname }}fullchain.pem'
    grafana_tls_key_path: '/etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem'
  roles:
    - role: prometheus
      tags: prometheus
    - role: grafana
      tags: grafana
    - role: prometheus-exporters
      tags: exporters
  tags: monitoring
