---
# More info: http://dev-sec.io/docs/
- src: https://github.com/dev-sec/ansible-os-hardening
  name: ansible-os-hardening

- src: https://github.com/dev-sec/ansible-ssh-hardening
  name: ansible-ssh-hardening
