---
- name: Apply security hardening to hosts.
  become: yes
  hosts: all
  roles:
    - role: ansible-os-hardening
      os_auth_pam_passwdqc_enable: false
      os_auth_pw_max_age: 1460
      os_auth_lockout_time: 300
      os_security_users_allow: ["kevin", "steve"]
      os_security_kernel_enable_core_dump: true
      os_security_suid_sgid_remove_from_unknown: true
      os_desktop_enable: false
      os_env_extra_user_paths: ['/home']
      os_auth_allow_homeless: true
      os_security_suid_sgid_blacklist: ['/bin/umount']
      os_security_suid_sgid_whitelist: ['/usr/bin/rlogin']
      os_filesystem_whitelist: ['vfat']
      sysctl_config:
        net.ipv4.ip_forward: 1
        net.ipv6.conf.all.forwarding: 0
        net.ipv6.conf.all.accept_ra: 0
        net.ipv6.conf.default.accept_ra: 0
        net.ipv4.conf.all.rp_filter: 1
        net.ipv4.conf.default.rp_filter: 1
        net.ipv4.icmp_echo_ignore_broadcasts: 1
        net.ipv4.icmp_ignore_bogus_error_responses: 1
        net.ipv4.icmp_ratelimit: 100
        net.ipv4.icmp_ratemask: 88089
        net.ipv6.conf.all.disable_ipv6: 1
        net.ipv4.conf.all.arp_ignore: 1
        net.ipv4.conf.all.arp_announce: 2
        net.ipv4.conf.all.shared_media: 1
        net.ipv4.conf.default.shared_media: 1
        net.ipv4.conf.all.accept_source_route: 0
        net.ipv4.conf.default.accept_source_route: 0
        net.ipv4.conf.default.accept_redirects: 0
        net.ipv4.conf.all.accept_redirects: 0
        net.ipv4.conf.all.secure_redirects: 0
        net.ipv4.conf.default.secure_redirects: 0
        net.ipv6.conf.default.accept_redirects: 0
        net.ipv6.conf.all.accept_redirects: 0
        net.ipv4.conf.all.send_redirects: 0
        net.ipv4.conf.default.send_redirects: 0
        net.ipv4.conf.all.log_martians: 0
        net.ipv6.conf.default.router_solicitations: 0
        net.ipv6.conf.default.accept_ra_rtr_pref: 0
        net.ipv6.conf.default.accept_ra_pinfo: 0
        net.ipv6.conf.default.accept_ra_defrtr: 0
        net.ipv6.conf.default.autoconf: 0
        net.ipv6.conf.default.dad_transmits: 0
        net.ipv6.conf.default.max_addresses: 1
        kernel.sysrq: 0
        fs.suid_dumpable: 0
        kernel.randomize_va_space: 2
      tags: security
    - role: ansible-ssh-hardening
      sftp_enabled: true
      ssh_compression: true
      ssh_print_motd: false
      ssh_client_alive_interval: 120
      ssh_client_alive_count: 5
      network_ipv6_enable: false
      ssh_allow_root_with_key: false
      ssh_allow_tcp_forwarding: false
      ssh_gateway_ports: false
      ssh_allow_agent_forwarding: false
      ssh_server_permit_environment_vars: ['PWD','HTTP_PROXY']
      ssh_client_password_login: true
      ssh_client_cbc_required: false
      ssh_client_weak_kex: false
      ssh_client_weak_hmac: false
      ssh_client_hardening: true
      ssh_server_cbc_required: false
      ssh_challengeresponseauthentication: true
      ssh_allow_users: 'kevin'
      ssh_allow_groups: 'kevin'
      ssh_deny_users: 'root'
      ssh_deny_groups: 'root'
      ssh_authorized_keys_file: '/home/%u/.ssh/authorized_keys'
      ssh_max_auth_retries: 5
      ssh_permit_tunnel: false
      ssh_print_last_log: true
      ssh_banner: true
      ssh_server_password_login: false
      ssh_server_weak_hmac: false
      ssh_server_enabled: true
      ssh_use_dns: false
      ssh_use_pam: true
      ssh_max_startups: '10:30:60'
      tags: security