---
- name: Set up stretch-backports.
  apt_repository:
    repo: 'deb http://ftp.ca.debian.org/debian/ stretch-backports main contrib non-free'
    state: present

- name: Install Prometheus node exporter and mtail.
  apt:
    name: "{{ item }}"
    default_release: stretch-backports
    update_cache: yes
    cache_valid_time: 3600
    state: latest
  with_items:
    - prometheus-node-exporter
    - mtail

- name: Install Python dependencies for prometheus-tor-exporter.
  pip:
    name: "{{ item }}"
  with_items:
    - prometheus_client
    - stem

- name: Copy code for prometheus-tor-exporter.py.
  copy:
    dest: /usr/local/bin/prometheus-tor-exporter.py
    src: prometheus-tor-exporter.py
    owner: root
    group: root
    mode: "0755"

- name: Copy prometheus-tor-exporter systemd service unit.
  copy:
    dest: "/etc/systemd/system/prometheus-tor-exporter.service"
    src: prometheus-tor-exporter.service
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd

- name: Install mtail configuration.
  copy:
    src: mtail
    dest: "/etc/default/mtail"
    owner: root
    group: root
    mode: "0644"

- name: Install mtail syslog parsing config.
  copy:
    src: syslog.mtail
    dest: "/etc/mtail/syslog.mtail"
    owner: root
    group: root
    mode: "0644"

- name: Install Go for dnsmasq_exporter.
  apt:
    name: golang
    default_release: stretch-backports
    update_cache: yes
    cache_valid_time: 3600
    state: latest

- name: Set Go environment variables.
  set_fact:
    GOPATH: "/usr/local/go"
    GOROOT: "/usr/lib/go"
    DNSMASQ_EXPORTER_SRC: "github.com/google/dnsmasq_exporter"

- name: Create GOPATH and GOROOT if they don't exist.
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  ignore_errors: yes
  with_items:
    - "{{ GOPATH }}"
    - "{{ GOROOT }}"

- name: Get, build and install dnsmasq_exporter.
  shell: "go {{ item }} {{ DNSMASQ_EXPORTER_SRC }}"
  args:
    executable: "/bin/bash"
  environment:
    GOROOT: "{{ GOROOT }}"
    GOPATH: "{{ GOPATH }}"
  changed_when: false
  #become_user: prometheus
  with_items:
    - 'get -u'
    - 'build'
    - 'install'
  tags: go

- name: Copy dnsmasq-exporter systemd service unit.
  copy:
    dest: "/etc/systemd/system/dnsmasq-exporter.service"
    src: dnsmasq-exporter.service
    owner: root
    group: root
    mode: "0644"
  notify: reload systemd

- name: Start Prometheus node exporter and mtail.
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - prometheus-node-exporter
    - mtail
    - prometheus-tor-exporter
    - dnsmasq-exporter

- name: Only allow the main server to access metrics.
  ufw:
    rule: allow
    from: "{{ lookup('dig', 'tordns.party.')}}"
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 9052
    - 9100
    - 9153
    - 3903
  tags: ufw
