---
- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
    enabled: yes

- name: restart resolvconf
  service:
    name: resolvconf
    state: restarted
    enabled: no

- name: reload ufw
  ufw:
    state: enabled
  
- name: restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted
    enabled: no

- name: restart NetworkManager
  service:
    name: NetworkManager
    state: restarted