---
- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
    enabled: yes

- name: stop resolvconf
  service:
    name: resolvconf
    state: stopped
    enabled: no

- name: enable ufw
  ufw:
    state: enabled

- name: stop systemd-resolved
  service:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: stop NetworkManager
  service:
    name: network-manager
    state: restarted

- name: restart tor
  service:
    name: tor
    state: restarted
    enabled: yes
