---
galaxy_info:
  author: Kevin Gallagher (@ageis)
  description: Installs Tor ("The Onion Router") daemon for anonymous networking.
  company: Calyx Institute
  license: MIT
  min_ansible_version: 2.4.3
  platforms:
    - name: Debian
      versions:
      - stretch
  categories:
    - system
dependencies: []