---
- name: Set up stretch-backports.
  apt_repository:
    repo: 'deb http://http.us.debian.org/debian/ stretch-backports main contrib non-free'
    filename: stretch-backports
    state: present

- name: Install Prometheus and Alertmanager and blackbox-exporter.
  apt:
    name: "{{ item }}"
    default_release: stretch-backports
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - prometheus
    - prometheus-alertmanager
    - prometheus-blackbox-exporter

- name: Install Prometheus configuration.
  template:
    src: prometheus.yml.j2
    dest: "/etc/prometheus/prometheus.yml"
    owner: root
    group: root
    mode: "0644"
  tags: prometheus-cfg
  notify: reload prometheus

- name: Install Alertmanager configuration.
  template:
    src: alertmanager.yml.j2
    dest: "/etc/prometheus/alertmanager.yml"
    owner: root
    group: root
    mode: "0644"
  tags: alertmanager-cfg
  notify: reload prometheus-alertmanager

- name: Install blackbox-exporter configuration.
  template:
    src: blackbox.yml.j2
    dest: "/etc/prometheus/blackbox.yml"
    owner: root
    group: root
    mode: "0644"
  tags: blackbox-cfg
  notify: restart prometheus-blackbox-exporter

- name: Create alerts directories.
  file:
    path: "/etc/prometheus/alerts"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Copy alerting configuration.
  copy:
    dest: "/etc/prometheus/alerts/{{ item }}.alerts.yml"
    src: "{{ item }}.alerts.yml"
    owner: root
    group: root
    mode: "0644"
  tags: alerts
  notify: reload prometheus
  with_items:
    - nodes

- name: Set prometheus startup options.
  lineinfile:
    dest: /etc/default/prometheus
    regexp: "^#?ARGS"
    line: "ARGS='--config.file=\"/etc/prometheus/prometheus.yml\" --web.route-prefix=\"/prometheus\" --web.external-url=\"{{ prometheus_external_url }}\" --log.level=\"{{ prometheus_log_level }}\"'"
    state: present
  
- name: Set prometheus-alertmanager startup options.
  lineinfile:
    dest: /etc/default/prometheus-alertmanager
    regexp: "^#?ARGS"
    line: "ARGS='-config.file=\"/etc/prometheus/alertmanager.yml\" -web.external-url=\"http://{{ prometheus_alertmanager_url }}\" -data.retention=\"500h\" -log.level=\"{{ prometheus_alertmanager_log_level }}\" -data.retention=\"500h\"'"
    state: present
  
- name: Set prometheus-blackbox-exporter startup options.
  lineinfile:
    dest: /etc/default/prometheus-blackbox-exporter
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: "^#?ARGS="
      line: "ARGS='--config.file=\"/etc/prometheus/blackbox.yml\" --log.level=\"{{ prometheus_blackbox_exporter_log_level }}\"'"
    - regexp: "^HTTP_PROXY"
      line: "HTTP_PROXY=\"http://127.0.0.1:8118\""
    - regexp: "^RES_OPTIONS"
      line: "RES_OPTIONS=\"debug\""

- include: nginx.yml
  tags: nginx

- name: Start Prometheus and Alertmanager and blackbox-exporter.
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - prometheus
    - prometheus-alertmanager
    - prometheus-blackbox-exporter
