---
- name: Limit the total size of journald logs.
  lineinfile:
    dest: /etc/systemd/journald.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: "{{ item.insertafter }}"
    state: present
  with_items:
    - regexp: "^#?SystemMaxUse="
      line: "SystemMaxUse=512M"
      insertafter: "^[Journal]"
    - regexp: "^#?SystemMaxFileSize="
      line: "SystemMaxFileSize=64M"
      insertafter: "^[Journal]"
    - regexp: "^#?LineMax="
      line: "LineMax=64k"
      insertafter: "^[Journal]"
  notify: restart systemd-journald